# Generated by Django 3.1.1 on 2020-10-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userprofile_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
