# Generated by Django 3.1.2 on 2020-10-08 20:54

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(validators=[app.validators.MinAgeValidator(18)]),
        ),
    ]
