# Generated by Django 3.1.2 on 2020-10-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201009_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userannoucements',
            name='announcement',
            field=models.TextField(max_length=280),
        ),
    ]
