# Generated by Django 3.1.2 on 2020-10-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201010_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(related_name='followed_by', to='app.UserProfile'),
        ),
    ]
