# Generated by Django 3.1.2 on 2020-10-19 23:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201016_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default=app.models.random_img, upload_to='profile_pics1603148557'),
        ),
    ]
