# Generated by Django 3.1.2 on 2020-10-19 23:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201019_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default=app.models.random_img, upload_to='profile_pics'),
        ),
    ]
