# Generated by Django 3.1.2 on 2020-10-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201019_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnnoucementsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user_files')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userannoucements')),
            ],
        ),
    ]
