# Generated by Django 3.1.2 on 2020-10-27 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_userannoucementsimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnnoucements',
            new_name='UserAnnoucement',
        ),
        migrations.RenameModel(
            old_name='UserAnnoucementsImages',
            new_name='UserAnnoucementsImage',
        ),
    ]
