# Generated by Django 3.1.2 on 2020-10-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201027_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userannoucement',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_files'),
        ),
        migrations.DeleteModel(
            name='UserAnnoucementsImage',
        ),
    ]
