# Generated by Django 3.1.2 on 2020-10-28 17:26

import app.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201028_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userannoucement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default=app.models.random_img, max_length=255),
        ),
    ]
